`_dynamic_info_firecrest_version` updated with new development
aiidateam/aiida-firecrest pull request #60
Opened 2024-08-20 12:08 UTC by khsrali

`/status/parameters` endpoint of firecrest api  is now updated with version value.
We fetch this way and drop the previous work around that was implemented.
Fixes:
https://github.com/aiidateam/aiida-firecrest/issues/43

2024-09-06 17:44 UTC, agoscinski requested changes
Are [these comments](https://github.com/aiidateam/aiida-firecrest/blob/ff9b65ef54b9767085b9baa64707003bcd17bdb4/aiida_firecrest/transport.py#L132-L135) still up do date with this PR?

I am a bit confused how the function `_dynamic_info_firecrest_version` works. You specify a version by the value, but if it is 0 then it tries to to retrieve the  version dynamically. I guess that it is `0` and not `None` confuses me, but fine. Maybe can you add a bit doc to it because `value` is not such a meaningful name?

 Why is [the echo](https://github.com/aiidateam/aiida-firecrest/blob/ff9b65ef54b9767085b9baa64707003bcd17bdb4/aiida_firecrest/transport.py#L184-L186) only done in case it is dynamically retrieved? Maybe you can add a comment there.

2024-09-06 17:44 UTC, agoscinski commented on tests/test_computer.py
> +    assert result == "10.10.10"
Maybe you can add tests for the raise of `BadParameter`

2024-09-06 17:44 UTC, agoscinski commented on tests/test_computer.py
> +    assert monkeypatch is not None
Is this because of the linter? Seems a bit random

2024-09-12 08:56 UTC, khsrali commented
Thanks a lot, @agoscinski for the review!



> Are [these comments](https://github.com/aiidateam/aiida-firecrest/blob/ff9b65ef54b9767085b9baa64707003bcd17bdb4/aiida_firecrest/transport.py#L132-L135) still up do date with this PR?

yes, they are from the past, removed.

> 
> I am a bit confused how the function `_dynamic_info_firecrest_version` works. You specify a version by the value, but if it is 0 then it tries to to retrieve the version dynamically. I guess that it is `0` and not `None` confuses me, but fine. Maybe can you add a bit doc to it because `value` is not such a meaningful name?

Changed to `None`, doc added. Please check if it's clear. It's basically a click callback function.

> Why is [the echo](https://github.com/aiidateam/aiida-firecrest/blob/ff9b65ef54b9767085b9baa64707003bcd17bdb4/aiida_firecrest/transport.py#L184-L186) only done in case it is dynamically retrieved? Maybe you can add a comment there.

Just to prevent verbosity. Usually when inputs are valid during setting up/configuring a computer in aiida, it remains quite. 
I added echo for cases that it has to check something from the server. As a confirmation.

2024-09-12 12:45 UTC, agoscinski commented on tests/test_computer.py
> +    with pytest.raises(BadParameter) as exc_info:
pytest has an argument to match the error message
```suggestion
    with pytest.raises(BadParameter, match=r".*FirecREST api version 0.0.0 is not supported.*")):
```

2024-09-12 12:45 UTC, agoscinski commented on tests/test_computer.py
> +    assert "FirecREST api version 0.0.0 is not supported" in str(exc_info.value)
see above
```suggestion
```

2024-09-12 12:48 UTC, agoscinski commented on tests/test_computer.py
> +    with pytest.raises(BadParameter) as exc_info:
```suggestion
    with pytest.raises(BadParameter, match=r".* Invalid input.*"):
```

2024-09-12 12:49 UTC, agoscinski commented on tests/test_computer.py
> +    assert "Invalid input" in str(exc_info.value)
```suggestion
    with pytest.raises(BadParameter, match=r".*Invalid input.*"):
        _dynamic_info_firecrest_version(ctx, None, "latest")
```

2024-09-12 12:50 UTC, agoscinski commented on tests/test_computer.py
> +    assert "FirecREST api version 0.0.0 is not supported" in str(exc_info.value)
pytest has an argument to match the error message
```suggestion
    with pytest.raises(BadParameter, match=r".*FirecREST api version 0.0.0 is not supported.*")):
       _dynamic_info_firecrest_version(ctx, None, "0.0.0")
```

2024-09-12 12:51 UTC, agoscinski commented
Looks clear to me, I just simplified the pytest a little bit, check out my commit

2024-09-12 12:52 UTC, agoscinski commented on tests/test_computer.py
> +    with pytest.raises(BadParameter, match=r".*FirecREST api version 0.0.0 is not supported.*")):
```suggestion
    with pytest.raises(BadParameter, match=r".*FirecREST api version 0.0.0 is not supported.*"):
```

2024-09-13 09:43 UTC, khsrali commented
> Looks clear to me, I just simplified the pytest a little bit, check out my commit

Very good @agoscinski, thanks a lot!

2024-09-13 09:46 UTC, merged